//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovelDownloader.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NovelDownloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap img_floppydisk {
            get {
                object obj = ResourceManager.GetObject("img_floppydisk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap img_interface {
            get {
                object obj = ResourceManager.GetObject("img_interface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap img_new {
            get {
                object obj = ResourceManager.GetObject("img_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap img_update {
            get {
                object obj = ResourceManager.GetObject("img_update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   The novel of ncode &quot;{0}&quot; has already been registered. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_AlreadyBeenRegistered {
            get {
                return ResourceManager.GetString("Msg_AlreadyBeenRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_Detail {
            get {
                return ResourceManager.GetString("Msg_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the {0} field. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_FieldInput {
            get {
                return ResourceManager.GetString("Msg_FieldInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finish に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_Finish {
            get {
                return ResourceManager.GetString("Msg_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_Information {
            get {
                return ResourceManager.GetString("Msg_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Novels with ncode &quot;{0}&quot; do not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_NcodeNotFound {
            get {
                return ResourceManager.GetString("Msg_NcodeNotFound", resourceCulture);
            }
        }
    }
}
